### ISSUE TITLE
Navigation delegate, Navigation decision

### ISSUE THREAD

**Issue by patel0712** [hlwhl/webview_cef#134]
Hello webview_cef team,

Hope you will thik about it,
i'm using webview_cef package for my desktop linux app and it works very good 
but there's one feature that is not available or possibly i'm not aware about it if it's exists

in my app i want controlled url navigation like webview_flutter plugin has
so please help me with this team.

because the webview_cef is quite good i'm not want to replace it if i can add NavigationDecision and NavigationDelegaet like logic in package.

please reply me.

Thank You.

**Comment by SinyimZhi** [comment]
I understand the function you mentioned, and CEF itself should be able to support it, but it needs to be connected to the relevant logic on the DART side. This may be the same thing mentioned in another issue #127, and it is very informative. Perhaps we can directly use the dart side code of flutterw_webview.

**Comment by patel0712** [comment]
Thank you for your response 
So can you please tell me when this will added to package and published?
Or can you guide me to way you mentioned above , because I'm new to this

**Comment by SinyimZhi** [comment]
I haven't started developing this feature yet, I may not have time to start until the end of the month. There is a preliminary idea that all URLs actively loaded by users will be fully implemented on the DART side. flutter_webview‘s code can be reused basically. Just add the corresponding interface associations in webview.dart and webview_manager.dart. On the C++side, it may be necessary to add some restrictions on page redirection in Class WebviewHandler and WebviewApp.

**Comment by patel0712** [comment]
I tried but not successful 
If possible please check this :

**Comment by patel0712** [comment]
I tried but it's not working 
Please check it once.
https://drive.google.com/file/d/1I09VjGADqhTBzHMQ47Rq-aYsi1L8nLCT/view?usp=drivesdk

**Comment by SinyimZhi** [comment]
Could you push the code to your own Fork and make a pull request? If you want to join us make this project better.

**Comment by patel0712** [comment]
Sure I have done and its working

**Comment by patel0712** [comment]
Also  can we talk to any other medium like whatssapp or any other so I can receive and see response if need your guidance?

**Comment by patel0712** [comment]
In my implementation when I enter url in text box then it will work but if the url is triggered by clicking or redirected then it's not working my device is in fault that's why I provide drive link
https://drive.google.com/file/d/1zKubrBkvVQCEk_lKEJz_anqS-nOrG3ej/view?usp=sharing


If possible please help me

**Comment by patel0712** [comment]
Hey , can you please see merge request and changes I have done in code for url interception but it's not work as expected in some cases  so  an you guide me to do that?

**Comment by patel0712** [comment]
Hey bro can you please  tell me that when you will complete implementing NavigationDelegate like feature in package I try but it's not working as expected.

**Comment by jeet-flutter10** [comment]
hi @SinyimZhi @cadivus @hlwhl 

is there any plan to add navigatiobn delegate in plugin in next release.
i tried to implement it but not successful. and i'm waiting for this feature for my project can you pls answer me.

Thank you.

**Comment by SinyimZhi** [comment]
> hi [@SinyimZhi](https://github.com/SinyimZhi) [@cadivus](https://github.com/cadivus) [@hlwhl](https://github.com/hlwhl)
> 
> is there any plan to add navigatiobn delegate in plugin in next release. i tried to implement it but not successful. and i'm waiting for this feature for my project can you pls answer me.
> 
> Thank you.

Sorry, I have been unable to continue supporting this project recently due to family, work, and other reasons. I will try to restore support as soon as possible.

**Comment by jeet-flutter10** [comment]
Hi @SinyimZhi ,

Understood.  Let me know when you're able to revisit this.  Thanks for letting me know.

In the mean time if you have time please look at this and tell me where i'm mistaken. Here is a forked repo of plugin.

https://github.com/patel0712/webview_cef.git

Thank you.

**Comment by scalveerne** [comment]
@jeet-flutter10 Un saludo, queria consultarte si has podido hacer funcionar tu app en macos y si ademas has intentado algo para el proceso de multiples perfiles usando CEF, yo logre hacer que funcionara el multi perfil pero antes de avanzar queria ver que tenias en tu fork a ver si lo puedo usar xD

**Comment by jeet-flutter10** [comment]
@scalveerne  In my forked repo, I attempted to implement a Navigation Delegate, where a callback passes the URL from native to Flutter, and from Flutter to native, an action is sent for that URL. Based on the action (whether to navigate or prevent the URL from rendering/loading), the behavior is controlled.

To achieve this, I overrode the onBeforeBrowse method.

However, I couldn't get it to work as expected. I'm not sure what the issue is. If you have any insights or can help troubleshoot this, I'd really appreciate it!

And Also i not have macos so i'm not able to answer that app working on macos.

**Comment by scalveerne** [comment]
@jeet-flutter10 Queria compartirte esto, creo creo que puede ser util. Te cuento un poco de mi contexto:

* Tenemos un navegador web, para efectos del ejemplo asumamos que es como Chrome
* Cuando nuestros usuarios navegan a sitios resulta que el evento `onUrlChanged` se ejecuta cada vez que un request interno ocurre, por ej: un iframe de validacion de robot como captcha
* Para solucionar esto porque nuestros usuarios quedan locos con esto modifique esto:

```
void WebviewHandler::OnLoadStart(CefRefPtr<CefBrowser> browser, CefRefPtr<CefFrame> frame,
                                 CefLoadHandler::TransitionType transition_type)
{
    // Solo notificar cuando se trate del frame principal
    if (onLoadStart && frame->IsMain())
    {
        onLoadStart(browser->GetIdentifier(), frame->GetURL());
    }
    return;
}
```

La verdad es que no se si este es tu problema pero espero esto pueda inspirar alguna solucion alternativa

**Comment by jeet-flutter10** [comment]
@scalveerne  Thanks for sharing your approach!

By default, whenever an HTTP request is created, it always passes through the onBeforeBrowse method first. Even if we use onLoadStart, the request will still go through onBeforeBrowse beforehand. So, in my use case, onBeforeBrowse aligns best because I need to cancel navigation before it loads.

That's why I specifically use onBeforeBrowse—to control navigation at an early stage.

However, I’m not entirely sure I understand your exact issue. Could you clarify it a bit more? 
give me your email for better communication.

**Comment by scalveerne** [comment]
@jeet-flutter10 

Roughly speaking, I just have a problem with Cloudflare, if you could help me with it I would be very happy, right now the development is stopped because the verification and the Cloudflare robot breaks using the plugin or even the repository example

If it's more convenient for you, here's my email: "harold.castro@scalboost.com." You can also give me yours to contact me. This is very important, and I would appreciate an additional view.
