### ISSUE TITLE
App Crashes on Debug Restart

### ISSUE THREAD

**Issue by bahricanyesil** [hlwhl/webview_cef#98]
It throws "[1229/150823.836608:FATAL:webview_handler.cc(35)] Check failed: !g_instance." error when you restarted the app and tried to show webview again.

**Comment by SinyimZhi** [comment]
This line is called when you try to get the singleton webview_handler ,but it has not yet been instantiated or has already been destroyed. I will try to reproduce it and see if there are any issues.

**Comment by bahricanyesil** [comment]
> This line is called when you try to get the singleton webview_handler ,but it has not yet been instantiated or has already been destroyed. I will try to reproduce it and see if there are any issues.

I think it's related to the call of "dispose". So, maybe there is no problem. If you are not able to reproduce, you can close the issue.

**Comment by bahricanyesil** [comment]
> This line is called when you try to get the singleton webview_handler ,but it has not yet been instantiated or has already been destroyed. I will try to reproduce it and see if there are any issues.

It may be related to the call of the "dispose" method. You can close the issue if you can not reproduce it.

**Comment by SinyimZhi** [comment]
@bahricanyesil  I can not reproduce it, and i think the problem is caused we have not support multi instance. I'm already work on multi instance support. There is a branch on my fork named multi_window, but the solutions is not good. It can't support multi flutter engine(most multi window solutions are based on multi flutter engine). It might need to adjust the code structure a few more times
